using UnityEngine;

// SpellType.cs
public enum SpellType
{
    None,
    ExampleSpell,
    Barrier,
    Downward,
    Upward,
    ErrorDegreeReduce,
    ErrorDegreeIncrease,
    TwoChainCast,
    ThreeChainCast,
    FiveChainCast,
    TwoMultiplier,
    ThreeMultiplier,
    FiveMultiplier,
    Expansion,
    Contraction,
    Inferno,
    ExampleSpellClickTrigger,
    IceShot,
    FireShot,
    IceBreak,
    IceDamage,
    FireDamage,
    WoodDamage,
    WaterDamage,
    AdditionalDamage,
    AdditionalKnockback,
    HealingDamage,
    Skip,
    Homing,
    HealShot,
    WaterShot,
    WoodShot,
}